### ISSUE TITLE
Website: Pages

### ISSUE THREAD

**Issue by srashtisj** [techvraksh/techvraksh.github.io#3]
- Home
- Services
- About Us
- - Team
    > Core Team
    > Interns
- Contact

**Comment by srashtisj** [comment]
illustration: https://undraw.co
Other resource: https://www.freepik.com

**Comment by ghost** [comment]
will note that 👍🏼

**Comment by saumya66** [comment]
Currently working on the NavBar adding appropriate links

**Comment by ghost** [comment]
@saumya66 just let me know once you are done

**Comment by saumya66** [comment]
I'm done @PulkitSinghDev , you can work on pages
